// Code generated by goctl. DO NOT EDIT.
package favorite

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/logic/favorite"
	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/svc"
)

func GetListHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := favorite.NewGetListLogic(r.Context(), svcCtx)
		data, err := l.GetList()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
