// Code generated by goctl. DO NOT EDIT.
package health

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/logic/health"
	"github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/svc"
)

func GetHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := health.NewGetLogic(r.Context(), svcCtx)
		data, err := l.Get()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
