// Code generated by goctl. DO NOT EDIT.
package file

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/logic/file"
	"github.com/vesoft-inc/nebula-studio/server-v2/api/studio/internal/svc"
)

func FileUploadHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := file.NewFileUploadLogic(r.Context(), svcCtx)
		err := l.FileUpload()
		svcCtx.ResponseHandler.Handle(w, r, nil, err)
	}
}
