// Code generated by goctl. DO NOT EDIT.
package test

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/logic/test"
	"github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/svc"
)

func TestHellworldHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := test.NewTestHellworldLogic(r.Context(), svcCtx)
		data, err := l.TestHellworld()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
