// Code generated by goctl. DO NOT EDIT.
package llm

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/logic/llm"
	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/svc"
)

func GetLLMConfigHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := llm.NewGetLLMConfigLogic(r.Context(), svcCtx)
		data, err := l.GetLLMConfig()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
