// Code generated by goctl. DO NOT EDIT.
package gateway

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/logic/gateway"
	"github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/svc"
)

func DisonnectHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := gateway.NewDisonnectLogic(r.Context(), svcCtx)
		data, err := l.Disonnect()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
