// Code generated by goctl. DO NOT EDIT.
package gpt

import (
	"net/http"

	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/logic/gpt"
	"github.com/vesoft-inc/nebula-studio/server/api/studio/internal/svc"
)

func GetGPTConfigHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		l := gpt.NewGetGPTConfigLogic(r.Context(), svcCtx)
		data, err := l.GetGPTConfig()
		svcCtx.ResponseHandler.Handle(w, r, data, err)
	}
}
