// Code generated by goctl. DO NOT EDIT.
package types

type AnyResp struct {
	Data interface{} `json:"data"`
}

type BatchExecGQLParams struct {
	Gqls []string `json:"gqls"`
}

type ConnectDBParams struct {
	Address       string `json:"address"`
	Port          int    `json:"port"`
	Authorization string `header:"Authorization"`
}

type ExecGQLParams struct {
	Gql string `json:"gql"`
}

type GetTestReq struct {
}

type GetTestResp struct {
	Data interface{} `json:"data,omitempty"`
}
