// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	gateway "github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/handler/gateway"
	test "github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/handler/test"
	"github.com/vesoft-inc/nebula-studio/server-v5/api/studio/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/connect",
				Handler: gateway.ConnectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/disconnect",
				Handler: gateway.DisonnectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api-studio/db"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/exec",
				Handler: gateway.ExecGQLHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api-studio/gql"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: test.TestHellworldHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api-studio"),
	)
}
