// Code generated by goctl. DO NOT EDIT.
package types

type GetHealth struct {
	Status string `json:"status"`
}

type ExecNGQLParams struct {
	Gql       string   `json:"gql"`
	ParamList []string `json:"paramList"`
}

type ConnectDBParams struct {
	Address       string `json:"address"`
	Port          int    `json:"port"`
	NebulaVersion string `form:"nebulaVersion,optional"`
	Authorization string `header:"Authorization"`
}

type ConnectDBResult struct {
	Version string `json:"version"`
}

type DisconnectDBParams struct {
	Nsid string `form:"nsid,optional"`
}

type AnyResponse struct {
	Data interface{} `json:"data"`
}

type FileDestroyRequest struct {
	Name string `path:"name" validate:"required"`
}

type FileStat struct {
	Content    [][]string `json:"content"`
	WithHeader bool       `json:"withHeader"`
	DataType   string     `json:"dataType"`
	Name       string     `json:"name"`
	Size       int64      `json:"size"`
}

type FilesIndexData struct {
	List []FileStat `json:"list"`
}
